### PR TITLE
Enable publishing of JUnit results by default

### PR DESCRIPTION
**Pull request by mikeharder**
I believe most of the pipeline templates publish test results by default, so I think the Java templates should do the same, unless there's a good reason not to.

### CODE REVIEW

**Comment by DavidStaheli** [comment]
Before we merge this...
We currently issue a build warning if test result publishing is enabled but no tests are found ([example](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/GradleV2/gradletask.ts#L46)).  This will cause new pipelines to get ugly warnings if they have no test results.  😢

I'd love to change that warning to informational output.  But that changes behavior, such as if a task runs conditionally based upon another task having no warnings.  So that probably warrants a new major version.  Do you agree?

**Comment by DavidStaheli** [comment]
Yes but it seems like the default task settings shouldn't result in a build with warnings.  Builds will be dirty for people just starting out.

**Comment by chrisrpatterson** [comment]
There is no way to conditionalize a task based on another task having warnings so that is not an issue as these warnings do not indicate partial success for the task.  That being said I agree that we should not have warnings for missing files.  However, we do need some way to indicate to the user that the pattern supplied does not match any files in the case that they did intend to publish test results but mistyped the patttern.

**Comment by leantk** [comment]
Closing this because it is old. @mikeharder if you are still looking to get this in, please re-open it and we will go over the pros/cons that were hashed out above

**Pull request closed without merging**
