### PR TITLE
Remove the trigger on 'master' in favor of [skip ci] on wizard commits

### PR DESCRIPTION
**Pull request by DavidStaheli**
The "New pipeline" wizard will now append `[skip ci]` to commits so that a **manually**-queued build still runs for a new pipeline, but a **CI** build will not.  With this, we can remove the explicit trigger on 'master' from the YAML templates since `[skip ci]` will have the desired effect.

### CODE REVIEW

**Comment by jayspadie** [comment]
So we've added [skip ci] to commits created by the YAML editor, but that's only part of the story for specifying only the trigger for master.  Removing the trigger will reintroduce CI builds for commits to every branch.  Do we really want to change that behavior?

**Comment by DavidStaheli** [comment]
Hmm, good point.  I think it will cause a CI build even for PR branches with commits that don't use [skip ci].

**Comment by jayspadie** [comment]
> Hmm, good point. I think it will cause a CI build even for PR branches with commits that don't use [skip ci].

Right... This goes beyond whatever our YAML editor does.  It changes the CI behavior for all commits in all branches (with or without a PR), triggering a build for each push.  Maybe some customers want this, but it's a big behavior change by default.

**Comment by madhurig** [comment]
We switched from not having the trigger to adding it and we didn't get any push back on that. I personally like having the trigger in the yml, it is very explicit and clear to the user why builds are triggered only on master branch.

**Comment by jayspadie** [comment]
Yes, to be clear, I like the trigger as well and I don't think we should remove it.  It gives the user clear awareness of the trigger option, it prevents the proliferation of unwanted builds, and the user can update it as they see fit.

**Comment by DavidStaheli** [comment]
Ba-bam.  Thanks for the feedback on this!

**Pull request closed without merging**
