### PR TITLE
Update spec for multiple nuget authentication tasks

### PR DESCRIPTION
**Pull request by zarenner**

### CODE REVIEW

**Comment by zarenner** [comment]
@elbatk updating this since it was out of date and confused @jcagme today

**Comment by elbatk** [comment]
@zarenner looks good, feel free to throw me on as a reviewer if you need.

**Comment by zarenner** [comment]
I don't seem to even have permission to add you as a reviewer - if you can do that and have permission to merge, please do.

**Comment by elbatk** [comment]
@zarenner i do not 🤔 . might have to bug @infin8x if he's feeling better tomorrow.

**Pull request merged**
